script:
  path: ./public/scripts
settings:
  application:
    domain: localhost:8000
    host: 0.0.0.0
    ishttps: false
    mode: dev
    name: testApp
    port: "8000"
    readtimeout: 1
    writertimeout: 2
  database:
    dbtype: mysql
    host: 127.0.0.1
    name: ferry_admin
    password: 123456
    port: 3306
    username: root
  jwt:
    secret: ferry
    timeout: 3600
  log:
    dir: temp/logs
    operdb: false
  ssl:
    key: keystring
    pem: temp/pem.pem
